clear buildings.csv

In [5]:
import pandas as pd

path = "buildings.csv"
bldg = pd.read_csv(path)

bldg.head()

,Census year,Block ID,Property ID,Base property ID,Building name,Street address,CLUE small area,Construction year,Refurbished year,Number of floors (above ground),Predominant space use,Accessibility type,Accessibility type description,Accessibility rating,Bicycle spaces,Has showers,Longitude,Latitude,location
0,2006,324,110251,110251,NaN,6 Wood Street NORTH MELBOURNE 3051,North Melbourne,NaN,NaN,2.0,House/Townhouse,Not determined or not applicable,Building is not considered to be publicly acce...,0.0,NaN,NaN,144.945891,-37.797250,"-37.79724975, 144.945891475"
1,2006,325,102911,102911,NaN,332-344 Dryburgh Street NORTH MELBOURNE 3051,North Melbourne,NaN,NaN,3.0,Residential Apartment,High level of accessibility,Main Entrance is at grade and has no steps or ...,3.0,NaN,NaN,144.944837,-37.797965,"-37.7979653, 144.944837169"
2,2006,326,102353,106681,NaN,175 Curzon Street NORTH MELBOURNE 3051,North Melbourne,NaN,NaN,3.0,Residential Apartment,Moderate level of accessibility,Main entrance has steps; Alternative entrance ...,2.0,NaN,NaN,144.947719,-37.798038,"-37.79803831, 144.947719479"
3,2006,326,104590,106681,NaN,30 Haines Street NORTH MELBOURNE 3051,North Melbourne,NaN,NaN,3.0,Residential Apartment,Low level of accessibility,All entrances have steps,1.0,NaN,NaN,144.947719,-37.798038,"-37.79803831, 144.947719479"
4,2006,327,100113,100113,NaN,302-326 Abbotsford Street NORTH MELBOURNE 3051,North Melbourne,NaN,NaN,3.0,Residential Apartment,Not determined or not applicable,Configuration of entrance does not fit into an...,0.0,NaN,NaN,144.946473,-37.799414,"-37.79941397, 144.946473081"

In [6]:
print("Rows and columns:", bldg.shape)

print("\nColumn names:")
print(bldg.columns.tolist())

print("\nData types:")
print(bldg.dtypes)

print("\nFirst 5 rows:")
display(bldg.head())

Rows and columns: (236898, 19)

Column names:
['Census year', 'Block ID', 'Property ID', 'Base property ID', 'Building name', 'Street address', 'CLUE small area', 'Construction year', 'Refurbished year', 'Number of floors (above ground)', 'Predominant space use', 'Accessibility type', 'Accessibility type description', 'Accessibility rating', 'Bicycle spaces', 'Has showers', 'Longitude', 'Latitude', 'location']

Data types:
Census year                          int64
Block ID                             int64
Property ID                          int64
Base property ID                     int64
Building name                       object
Street address                      object
CLUE small area                     object
Construction year                  float64
Refurbished year                   float64
Number of floors (above ground)    float64
Predominant space use               object
Accessibility type                  object
Accessibility type description      object
Accessibility rating               float64
Bicycle spaces                     float64
Has showers                        float64
Longitude                          float64
Latitude                           float64
location                            object
dtype: object

First 5 rows:

,Census year,Block ID,Property ID,Base property ID,Building name,Street address,CLUE small area,Construction year,Refurbished year,Number of floors (above ground),Predominant space use,Accessibility type,Accessibility type description,Accessibility rating,Bicycle spaces,Has showers,Longitude,Latitude,location
0,2006,324,110251,110251,NaN,6 Wood Street NORTH MELBOURNE 3051,North Melbourne,NaN,NaN,2.0,House/Townhouse,Not determined or not applicable,Building is not considered to be publicly acce...,0.0,NaN,NaN,144.945891,-37.797250,"-37.79724975, 144.945891475"
1,2006,325,102911,102911,NaN,332-344 Dryburgh Street NORTH MELBOURNE 3051,North Melbourne,NaN,NaN,3.0,Residential Apartment,High level of accessibility,Main Entrance is at grade and has no steps or ...,3.0,NaN,NaN,144.944837,-37.797965,"-37.7979653, 144.944837169"
2,2006,326,102353,106681,NaN,175 Curzon Street NORTH MELBOURNE 3051,North Melbourne,NaN,NaN,3.0,Residential Apartment,Moderate level of accessibility,Main entrance has steps; Alternative entrance ...,2.0,NaN,NaN,144.947719,-37.798038,"-37.79803831, 144.947719479"
3,2006,326,104590,106681,NaN,30 Haines Street NORTH MELBOURNE 3051,North Melbourne,NaN,NaN,3.0,Residential Apartment,Low level of accessibility,All entrances have steps,1.0,NaN,NaN,144.947719,-37.798038,"-37.79803831, 144.947719479"
4,2006,327,100113,100113,NaN,302-326 Abbotsford Street NORTH MELBOURNE 3051,North Melbourne,NaN,NaN,3.0,Residential Apartment,Not determined or not applicable,Configuration of entrance does not fit into an...,0.0,NaN,NaN,144.946473,-37.799414,"-37.79941397, 144.946473081"

In [7]:
miss = pd.DataFrame({
    "missingcount": bldg.isna().sum(),
    "missingpercent": bldg.isna().mean() * 100
}).sort_values("missingpercent", ascending=False)

display(miss)

                                 missingcount  missingpercent
Has showers                            236898      100.000000
Refurbished year                       207151       87.443119
Building name                          191102       80.668473
Bicycle spaces                         175797       74.207887
Construction year                      114940       48.518772
Accessibility type description          26412       11.149102
Accessibility rating                    26412       11.149102
Accessibility type                      26411       11.148680
Latitude                                 2860        1.207271
location                                 2860        1.207271
Longitude                                2860        1.207271
Number of floors (above ground)            72        0.030393
Property ID                                 0        0.000000
Census year                                 0        0.000000
Block ID                                    0        0.000000
Predominant space use                       0        0.000000
Base property ID                            0        0.000000
Street address                              0        0.000000
CLUE small area                             0        0.000000

In [8]:
dups = bldg.duplicated().sum()

print("Duplicate rows:", dups)

Duplicate rows: 0

In [9]:
desc = bldg.describe(include="all").T

display(desc)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Census year,236898.0,NaN,NaN,NaN,2013.260074,6.347863,2002.0,2008.0,2014.0,2019.0,2024.0
Block ID,236898.0,NaN,NaN,NaN,604.614699,616.508619,1.0,247.0,420.0,657.0,2547.0
Property ID,236898.0,NaN,NaN,NaN,239687.647122,7119347.80652,0.0,103634.0,107264.0,111017.0,2000001109.0
Base property ID,236898.0,NaN,NaN,NaN,206930.552276,198534.383861,100001.0,103587.0,107110.0,110597.0,727623.0
Building name,45796,4125,Merrim Terrace,212,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Street address,236898,29403,2 Swanston Street MELBOURNE 3000,159,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CLUE small area,236898,13,Kensington,51735,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Construction year,121958.0,NaN,NaN,NaN,1944.136326,49.301881,1837.0,1900.0,1943.0,1994.0,2024.0
Refurbished year,29747.0,NaN,NaN,NaN,1996.400141,12.788569,1870.0,1990.0,1997.0,2003.0,2023.0
Number of floors (above ground),236826.0,NaN,NaN,NaN,2.696959,4.295751,1.0,1.0,2.0,2.0,101.0
Predominant space use,236898,28,House/Townhouse,140782,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Accessibility type,210487,5,Not determined or not applicable,127180,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Accessibility type description,210486,8,Building is not considered to be publicly acce...,121185,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Accessibility rating,210486.0,NaN,NaN,NaN,0.702493,1.041484,0.0,0.0,0.0,1.0,3.0
Bicycle spaces,61101.0,NaN,NaN,NaN,5.099442,39.433807,0.0,0.0,0.0,0.0,1800.0
Has showers,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Longitude,234038.0,NaN,NaN,NaN,144.953028,0.019873,144.89992,144.940183,144.953164,144.968225,144.990798
Latitude,234038.0,NaN,NaN,NaN,-37.804051,0.012322,-37.849737,-37.810949,-37.801142,-37.795222,-37.775825
location,234038,43423,"-37.79956857, 144.93036433",346,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
print(bldg["Census year"].min())
print(bldg["Census year"].max())

yr = bldg["Census year"].max()
bld = bldg[
    bldg["Census year"] == yr
].copy()

print("Latest year:", yr)
print("Rows:", bld.shape)

2002
2024
Latest year: 2024
Rows: (9376, 19)

In [11]:
drop_col = [
    "Has showers",
    "Refurbished year",
    "Bicycle spaces"
]

bld = bld.drop(
    columns=drop_col,
    errors="ignore"
)

print(bld.columns.tolist())

['Census year', 'Block ID', 'Property ID', 'Base property ID', 'Building name', 'Street address', 'CLUE small area', 'Construction year', 'Number of floors (above ground)', 'Predominant space use', 'Accessibility type', 'Accessibility type description', 'Accessibility rating', 'Longitude', 'Latitude', 'location']

In [12]:
bld = bld.dropna(
    subset=["Latitude", "Longitude"]
).copy()

print("Rows with coordinates:", len(bld))

Rows with coordinates: 9376

In [13]:
uses = bld["Predominant space use"].value_counts(
    dropna=False
)

display(uses)

Predominant space use
House/Townhouse                            5786
Residential Apartment                       944
Office                                      529
Unoccupied - Unused                         459
Entertainment/Recreation - Indoor           385
Retail - Shop                               206
Educational/Research                        158
Storage                                     142
Commercial Accommodation                    112
Equipment Installation                       92
Workshop/Studio                              71
Student Accommodation                        71
Hospital/Clinic                              57
Performances, Conferences, Ceremonies        52
Unoccupied - Under Construction              49
Parking - Commercial Covered                 38
Manufacturing                                29
Parking - Private Covered                    28
Wholesale                                    28
Unoccupied - Under Renovation                28
Community Use                                21
Institutional Accommodation                  20
Public Display Area                          18
Unoccupied - Under Demolition/Condemned      14
Retail - Showroom                            14
Retail - Stall                               11
Transport                                     9
Retail - Cars                                 5
Name: count, dtype: int64

In [14]:
keep_use = [
    "Community Use",
    "Public Display Area",
    "Educational/Research"
]

cand = bld[
    bld["Predominant space use"].isin(keep_use)
].copy()

print("Candidate buildings:", len(cand))

display(
    cand[
        [
            "Building name",
            "Street address",
            "Predominant space use",
            "Accessibility type",
            "Accessibility rating",
            "Latitude",
            "Longitude"
        ]
    ].head(30)
)

Candidate buildings: 197

,Building name,Street address,Predominant space use,Accessibility type,Accessibility rating,Latitude,Longitude
52984,NaN,44-54 University Street CARLTON VIC 3053,Educational/Research,Low level of accessibility,1.0,-37.799338,144.968109
53317,Building 248 - Peter Doherty Institute,786-798 Elizabeth Street MELBOURNE VIC 3000,Educational/Research,High level of accessibility,3.0,-37.800077,144.958253
53324,The University of Melbourne - Building 206,214 Berkeley Street CARLTON VIC 3053,Educational/Research,Low level of accessibility,1.0,-37.800471,144.959011
53325,The University of Melbourne Building 204,208-210 Berkeley Street CARLTON VIC 3053,Educational/Research,Low level of accessibility,1.0,-37.800630,144.958980
53326,The University of Melbourne - Building 207,202-206 Berkeley Street CARLTON VIC 3053,Educational/Research,High level of accessibility,3.0,-37.800740,144.958988
53327,Melbourne University - Building 260,Building 260 (MSHS) 182-200 Berkeley Street CA...,Educational/Research,Low level of accessibility,1.0,-37.801046,144.958934
53330,"Melbourne University - Building 261, 250 & 379",Melbourne University 197-235 Bouverie Street C...,Educational/Research,High level of accessibility,3.0,-37.801178,144.961518
53336,Building 243,715-721 Swanston Street CARLTON VIC 3053,Educational/Research,Low level of accessibility,1.0,-37.801150,144.963405
53365,NaN,246-252 Lygon Street CARLTON VIC 3053,Educational/Research,Low level of accessibility,1.0,-37.801377,144.967324
53383,Melbourne Museum,Melbourne Museum 11 Nicholson Street CARLTON V...,Public Display Area,High level of accessibility,3.0,-37.804019,144.971636
53438,Building 246,546-552 Swanston Street CARLTON VIC 3053,Educational/Research,High level of accessibility,3.0,-37.803874,144.963936
53446,Metropolitan Fire Brigade Station No.3,MFB Station No.3 104-114 Bouverie Street CARLT...,Community Use,High level of accessibility,3.0,-37.803947,144.962377
53457,Bldg 263 - Kwong Lee Dow,Melbourne University 224-252 Queensberry Stree...,Educational/Research,Not determined or not applicable,0.0,-37.803957,144.961002
53465,Building 106 Law Building,Melbourne University Building C 179-201 Pelham...,Educational/Research,High level of accessibility,3.0,-37.802410,144.960034
53507,RMIT Building 94,23-37 Cardigan Street CARLTON VIC 3053,Educational/Research,Not determined or not applicable,0.0,-37.805935,144.963958
53508,RMIT- George Thompson - Building 55,George Thompson - RMIT Building 55 58-80 Cardi...,Educational/Research,High level of accessibility,3.0,-37.805156,144.964975
53516,RMIT - Building 51(Frederick Campbell),Frederick Campbell - RMIT Building 51 80-92 Vi...,Educational/Research,Moderate level of accessibility,2.0,-37.806580,144.964831
53547,Building 143,Building 143 230 Grattan Street PARKVILLE VIC ...,Educational/Research,Moderate level of accessibility,2.0,-37.797388,144.961259
53548,Grainger Museum Building 140,Grainger Museum Building 140 230 Grattan Stree...,Public Display Area,High level of accessibility,3.0,-37.797388,144.961259
53549,Old Metallurgy Building 166,Old Metallurgy Building 166 230 Grattan Street...,Educational/Research,Moderate level of accessibility,2.0,-37.797388,144.961259
53550,1888 Building 198,1888 Building 198 230 Grattan Street PARKVILLE...,Educational/Research,Moderate level of accessibility,2.0,-37.797388,144.961259
53551,Old Quad Building 150,Old Quad Building 150 230 Grattan Street PARKV...,Educational/Research,High level of accessibility,3.0,-37.797388,144.961259
53553,Chemistry Building 153,Chemistry Building 153 230 Grattan Street PARK...,Educational/Research,Moderate level of accessibility,2.0,-37.797388,144.961259
53554,MSD Building 133,MSD Building 133 230 Grattan Street PARKVILLE ...,Educational/Research,High level of accessibility,3.0,-37.797388,144.961259
53555,Redmond Barry Building 115,Redmond Barry Building 115 230 Grattan Street ...,Educational/Research,Moderate level of accessibility,2.0,-37.797388,144.961259
53557,Babel Building 139,Babel Building 139 230 Grattan Street PARKVILL...,Educational/Research,High level of accessibility,3.0,-37.797388,144.961259
53558,Howard Florey Building 183,Howard Florey Building 183 230 Grattan Street ...,Educational/Research,High level of accessibility,3.0,-37.797388,144.961259
53559,Bldg 184 Melbourne Integrative Genomics,Melbourne Integrative Genomics Building 184 23...,Educational/Research,High level of accessibility,3.0,-37.797388,144.961259
53562,NaN,Arts & Culture Building 159 University of Melb...,Educational/Research,High level of accessibility,3.0,-37.797388,144.961259
53611,St.Michael's Primary School,4-18 Brougham Street NORTH MELBOURNE VIC 3051,Educational/Research,Moderate level of accessibility,2.0,-37.793415,144.946283

In [15]:
libr_b = bld[
    bld["Building name"].str.contains(
        "Library",
        case=False,
        na=False
    )
    |
    bld["Street address"].str.contains(
        "Library",
        case=False,
        na=False
    )
].copy()

print("Library buildings:", len(libr_b))

display(
    libr_b[
        [
            "Building name",
            "Street address",
            "Predominant space use",
            "Accessibility type",
            "Accessibility rating",
            "Latitude",
            "Longitude"
        ]
    ]
)

Library buildings: 3

,Building name,Street address,Predominant space use,Accessibility type,Accessibility rating,Latitude,Longitude
167406,East Melbourne Library,East Melbourne Library 120-126 George Street E...,Public Display Area,High level of accessibility,3.0,-37.815064,144.986387
169573,Athenaeum Library and Theatre,184-192 Collins Street MELBOURNE VIC 3000,"Performances, Conferences, Ceremonies",High level of accessibility,3.0,-37.814856,144.967278
169998,Kathleen Syme Centre,Kathleen Syme Library and Community Centre 249...,Community Use,High level of accessibility,3.0,-37.798721,144.965258

In [16]:
bld_ref = pd.concat(
    [cand, libr_b],
    ignore_index=True
)

bld_ref = bld_ref.drop_duplicates(
    subset=["Property ID", "Latitude", "Longitude"]
)

print("Building candidates:", len(bld_ref))

display(
    bld_ref[
        [
            "Building name",
            "Street address",
            "Predominant space use",
            "Accessibility type",
            "Accessibility rating",
            "Latitude",
            "Longitude"
        ]
    ].head(30)
)

Building candidates: 198

,Building name,Street address,Predominant space use,Accessibility type,Accessibility rating,Latitude,Longitude
0,NaN,44-54 University Street CARLTON VIC 3053,Educational/Research,Low level of accessibility,1.0,-37.799338,144.968109
1,Building 248 - Peter Doherty Institute,786-798 Elizabeth Street MELBOURNE VIC 3000,Educational/Research,High level of accessibility,3.0,-37.800077,144.958253
2,The University of Melbourne - Building 206,214 Berkeley Street CARLTON VIC 3053,Educational/Research,Low level of accessibility,1.0,-37.800471,144.959011
3,The University of Melbourne Building 204,208-210 Berkeley Street CARLTON VIC 3053,Educational/Research,Low level of accessibility,1.0,-37.800630,144.958980
4,The University of Melbourne - Building 207,202-206 Berkeley Street CARLTON VIC 3053,Educational/Research,High level of accessibility,3.0,-37.800740,144.958988
5,Melbourne University - Building 260,Building 260 (MSHS) 182-200 Berkeley Street CA...,Educational/Research,Low level of accessibility,1.0,-37.801046,144.958934
6,"Melbourne University - Building 261, 250 & 379",Melbourne University 197-235 Bouverie Street C...,Educational/Research,High level of accessibility,3.0,-37.801178,144.961518
7,Building 243,715-721 Swanston Street CARLTON VIC 3053,Educational/Research,Low level of accessibility,1.0,-37.801150,144.963405
8,NaN,246-252 Lygon Street CARLTON VIC 3053,Educational/Research,Low level of accessibility,1.0,-37.801377,144.967324
9,Melbourne Museum,Melbourne Museum 11 Nicholson Street CARLTON V...,Public Display Area,High level of accessibility,3.0,-37.804019,144.971636
10,Building 246,546-552 Swanston Street CARLTON VIC 3053,Educational/Research,High level of accessibility,3.0,-37.803874,144.963936
11,Metropolitan Fire Brigade Station No.3,MFB Station No.3 104-114 Bouverie Street CARLT...,Community Use,High level of accessibility,3.0,-37.803947,144.962377
12,Bldg 263 - Kwong Lee Dow,Melbourne University 224-252 Queensberry Stree...,Educational/Research,Not determined or not applicable,0.0,-37.803957,144.961002
13,Building 106 Law Building,Melbourne University Building C 179-201 Pelham...,Educational/Research,High level of accessibility,3.0,-37.802410,144.960034
14,RMIT Building 94,23-37 Cardigan Street CARLTON VIC 3053,Educational/Research,Not determined or not applicable,0.0,-37.805935,144.963958
15,RMIT- George Thompson - Building 55,George Thompson - RMIT Building 55 58-80 Cardi...,Educational/Research,High level of accessibility,3.0,-37.805156,144.964975
16,RMIT - Building 51(Frederick Campbell),Frederick Campbell - RMIT Building 51 80-92 Vi...,Educational/Research,Moderate level of accessibility,2.0,-37.806580,144.964831
17,Building 143,Building 143 230 Grattan Street PARKVILLE VIC ...,Educational/Research,Moderate level of accessibility,2.0,-37.797388,144.961259
18,Grainger Museum Building 140,Grainger Museum Building 140 230 Grattan Stree...,Public Display Area,High level of accessibility,3.0,-37.797388,144.961259
19,Old Metallurgy Building 166,Old Metallurgy Building 166 230 Grattan Street...,Educational/Research,Moderate level of accessibility,2.0,-37.797388,144.961259
20,1888 Building 198,1888 Building 198 230 Grattan Street PARKVILLE...,Educational/Research,Moderate level of accessibility,2.0,-37.797388,144.961259
21,Old Quad Building 150,Old Quad Building 150 230 Grattan Street PARKV...,Educational/Research,High level of accessibility,3.0,-37.797388,144.961259
22,Chemistry Building 153,Chemistry Building 153 230 Grattan Street PARK...,Educational/Research,Moderate level of accessibility,2.0,-37.797388,144.961259
23,MSD Building 133,MSD Building 133 230 Grattan Street PARKVILLE ...,Educational/Research,High level of accessibility,3.0,-37.797388,144.961259
24,Redmond Barry Building 115,Redmond Barry Building 115 230 Grattan Street ...,Educational/Research,Moderate level of accessibility,2.0,-37.797388,144.961259
25,Babel Building 139,Babel Building 139 230 Grattan Street PARKVILL...,Educational/Research,High level of accessibility,3.0,-37.797388,144.961259
26,Howard Florey Building 183,Howard Florey Building 183 230 Grattan Street ...,Educational/Research,High level of accessibility,3.0,-37.797388,144.961259
27,Bldg 184 Melbourne Integrative Genomics,Melbourne Integrative Genomics Building 184 23...,Educational/Research,High level of accessibility,3.0,-37.797388,144.961259
28,NaN,Arts & Culture Building 159 University of Melb...,Educational/Research,High level of accessibility,3.0,-37.797388,144.961259
29,St.Michael's Primary School,4-18 Brougham Street NORTH MELBOURNE VIC 3051,Educational/Research,Moderate level of accessibility,2.0,-37.793415,144.946283

In [17]:
bld_final = bld_ref[
    bld_ref["Predominant space use"].isin(
        ["Community Use", "Public Display Area"]
    )
    |
    bld_ref["Building name"].str.contains(
        "Library",
        case=False,
        na=False
    )
].copy()

print("Refined building candidates:", len(bld_final))

display(
    bld_final[
        [
            "Building name",
            "Street address",
            "Predominant space use",
            "Accessibility type",
            "Accessibility rating",
            "Latitude",
            "Longitude"
        ]
    ].head(50)
)

Refined building candidates: 40

,Building name,Street address,Predominant space use,Accessibility type,Accessibility rating,Latitude,Longitude
9,Melbourne Museum,Melbourne Museum 11 Nicholson Street CARLTON V...,Public Display Area,High level of accessibility,3.0,-37.804019,144.971636
11,Metropolitan Fire Brigade Station No.3,MFB Station No.3 104-114 Bouverie Street CARLT...,Community Use,High level of accessibility,3.0,-37.803947,144.962377
18,Grainger Museum Building 140,Grainger Museum Building 140 230 Grattan Stree...,Public Display Area,High level of accessibility,3.0,-37.797388,144.961259
30,NaN,1-3 Boundary Road NORTH MELBOURNE VIC 3051,Community Use,High level of accessibility,3.0,-37.797014,144.938100
35,NaN,133-139 Capel Street NORTH MELBOURNE VIC 3051,Community Use,Low level of accessibility,1.0,-37.804791,144.954877
39,NaN,187-189 Victoria Street WEST MELBOURNE VIC 3003,Community Use,High level of accessibility,3.0,-37.806039,144.955345
41,Fairhall,152-156 Hotham Street EAST MELBOURNE VIC 3002,Public Display Area,Low level of accessibility,1.0,-37.813827,144.985100
43,Australian Centre for Contemporary Art,Australian Centre Contemporary Art 101-111 Stu...,Public Display Area,High level of accessibility,3.0,-37.826563,144.967170
46,Melbourne Exhibition Centre,Melbourne Exhibition Centre 2 Clarendon Street...,Public Display Area,Not determined or not applicable,0.0,-37.825400,144.952378
47,La Trobes Cottage,La Trobe's Cottage 37 Dallas Brooks Drive MELB...,Public Display Area,Low level of accessibility,1.0,-37.831827,144.977156
53,Northern Pavillion,Northern Pavilion Fawkner Park Off Toorak Road...,Community Use,Low level of accessibility,1.0,-37.841025,144.981738
58,Flemington Oval Pavilion,Flemington Oval Pavilion Royal Park 54 Fleming...,Community Use,High level of accessibility,3.0,-37.786386,144.950920
59,NaN,749-755 Collins Street DOCKLANDS VIC 3008,Public Display Area,High level of accessibility,3.0,-37.821328,144.948575
60,NaN,91-101 Boundary Road NORTH MELBOURNE VIC 3051,Community Use,High level of accessibility,3.0,-37.791540,144.938842
64,Kensington Neighbourhood House,Kensington Neighbourhood House 89 McCracken St...,Community Use,Moderate level of accessibility,2.0,-37.793244,144.928006
93,Metropolitan Fire Brigade Station No.2,58-64 Batman Street WEST MELBOURNE VIC 3003,Community Use,High level of accessibility,3.0,-37.810551,144.951011
94,PUBLIC TOILETS,Queen Vic Market Toilets Queen Victoria Market...,Community Use,High level of accessibility,3.0,-37.807657,144.957205
95,Public Toilets,465 Queen Street MELBOURNE VIC 3000,Community Use,High level of accessibility,3.0,-37.807657,144.957205
106,Royal Exhibition Building,Royal Exhibition Building 9 Nicholson Street C...,Public Display Area,High level of accessibility,3.0,-37.804019,144.971636
125,Northern Pavilion,Northern Sports Pavilion Princes Park 360 Roya...,Community Use,Low level of accessibility,1.0,-37.785090,144.961398
131,NaN,67-69 Capel Street WEST MELBOURNE VIC 3003,Public Display Area,Low level of accessibility,1.0,-37.806529,144.954697
133,Melbourne Assessment Prison,Melbourne Assessment Prison 317-353 Spencer St...,Community Use,Moderate level of accessibility,2.0,-37.812785,144.950458
135,NaN,81 Altona Street KENSINGTON VIC 3031,Community Use,High level of accessibility,3.0,-37.797941,144.924041
137,East Melbourne Library,East Melbourne Library 120-126 George Street E...,Public Display Area,High level of accessibility,3.0,-37.815064,144.986387
138,Conservatory,Conservatory Fitzroy Gardens Wellington Parade...,Public Display Area,High level of accessibility,3.0,-37.812962,144.980456
140,Metropolitan Fire Brigade,MFB Station No.38 26-40 Moray Street SOUTHBANK...,Community Use,Moderate level of accessibility,2.0,-37.827178,144.960213
143,National Gallery of Victoria,NGV International 130-200 St Kilda Road SOUTHB...,Public Display Area,High level of accessibility,3.0,-37.822817,144.968634
146,Queen Victoria Gardens,Queen Victoria Gardens St Kilda Road MELBOURNE...,Community Use,Not determined or not applicable,0.0,-37.821884,144.971196
147,Edmund Herring Pavilion,Edmund Herring Pavilion Kings Domain South 19 ...,Community Use,Moderate level of accessibility,2.0,-37.831827,144.977156
149,Southern Pavillion,Southern Pavilion Fawkner Park Off Commercial ...,Community Use,Low level of accessibility,1.0,-37.841025,144.981738
160,Newmarket Pavilion,Newmarket Pavilion 26 Smithfield Road KENSINGT...,Community Use,Low level of accessibility,1.0,-37.788098,144.923097
161,Kensington Neighbourhood Centre,18 Anthony Street KENSINGTON VIC 3031,Community Use,High level of accessibility,3.0,-37.789395,144.928609
164,Flinders Street Station,Flinders Street Railway Station 207-361 Flinde...,Public Display Area,Not determined or not applicable,0.0,-37.818663,144.965470
165,Northbank,Northbank Flinders Walk MELBOURNE VIC 3000,Public Display Area,Not determined or not applicable,0.0,-37.819222,144.965150
166,Immigration Museum,Immigration Museum 400-424 Flinders Street MEL...,Public Display Area,Moderate level of accessibility,2.0,-37.819042,144.960359
176,Museum of Chinese Australian History,The Museum Of Australian Chinese History 20-24...,Public Display Area,High level of accessibility,3.0,-37.810737,144.969216
182,Royal Mint,Former Royal Mint Building 280 William Street ...,Public Display Area,High level of accessibility,3.0,-37.812090,144.957361
192,Old Melbourne Gaol,Old Melbourne Gaol 377 Russell Street MELBOURN...,Public Display Area,High level of accessibility,3.0,-37.807828,144.965252
196,Kathleen Syme Centre,Kathleen Syme Library and Community Centre 249...,Community Use,High level of accessibility,3.0,-37.798721,144.965258
198,Athenaeum Library and Theatre,184-192 Collins Street MELBOURNE VIC 3000,"Performances, Conferences, Ceremonies",High level of accessibility,3.0,-37.814856,144.967278

In [18]:
print("Final candidate rows:", len(bld_final))

print("\nSpace use:")
print(
    bld_final["Predominant space use"].value_counts()
)

print("\nAccessibility:")
print(
    bld_final["Accessibility type"].value_counts(
        dropna=False
    )
)

Final candidate rows: 40

Space use:
Predominant space use
Community Use                            21
Public Display Area                      18
Performances, Conferences, Ceremonies     1
Name: count, dtype: int64

Accessibility:
Accessibility type
High level of accessibility         23
Low level of accessibility           8
Moderate level of accessibility      5
Not determined or not applicable     4
Name: count, dtype: int64

In [19]:
print(
    "Missing building names:",
    bld_final["Building name"].isna().sum()
)

Missing building names: 7

In [20]:
no_name = bld_final[
    bld_final["Building name"].isna()
].copy()

display(
    no_name[
        [
            "Street address",
            "Predominant space use",
            "Accessibility type",
            "Accessibility rating",
            "Latitude",
            "Longitude"
        ]
    ]
)

,Street address,Predominant space use,Accessibility type,Accessibility rating,Latitude,Longitude
30,1-3 Boundary Road NORTH MELBOURNE VIC 3051,Community Use,High level of accessibility,3.0,-37.797014,144.938100
35,133-139 Capel Street NORTH MELBOURNE VIC 3051,Community Use,Low level of accessibility,1.0,-37.804791,144.954877
39,187-189 Victoria Street WEST MELBOURNE VIC 3003,Community Use,High level of accessibility,3.0,-37.806039,144.955345
59,749-755 Collins Street DOCKLANDS VIC 3008,Public Display Area,High level of accessibility,3.0,-37.821328,144.948575
60,91-101 Boundary Road NORTH MELBOURNE VIC 3051,Community Use,High level of accessibility,3.0,-37.791540,144.938842
131,67-69 Capel Street WEST MELBOURNE VIC 3003,Public Display Area,Low level of accessibility,1.0,-37.806529,144.954697
135,81 Altona Street KENSINGTON VIC 3031,Community Use,High level of accessibility,3.0,-37.797941,144.924041

In [21]:
review_b = bld_final[
    bld_final["Building name"].isna()
].copy()

bld_final = bld_final[
    bld_final["Building name"].notna()
].copy()

print("Need manual review:", len(review_b))
print("Named candidates:", len(bld_final))

Need manual review: 7
Named candidates: 33

In [22]:
review_b.to_csv(
    "buildings_missing_names_review.csv",
    index=False
)

In [23]:
odd_use = bld_final[
    bld_final["Predominant space use"].isin(
        [
            "Unoccupied - Under Construction",
            "Performances, Conferences, Ceremonies"
        ]
    )
]

display(
    odd_use[
        [
            "Building name",
            "Street address",
            "Predominant space use",
            "Accessibility type",
            "Accessibility rating"
        ]
    ]
)

,Building name,Street address,Predominant space use,Accessibility type,Accessibility rating
198,Athenaeum Library and Theatre,184-192 Collins Street MELBOURNE VIC 3000,"Performances, Conferences, Ceremonies",High level of accessibility,3.0

In [24]:
bld_final = bld_final[
    ~(
        bld_final["Building name"].eq(
            "State Library Rail Station"
        )
        &
        bld_final["Predominant space use"].eq(
            "Unoccupied - Under Construction"
        )
    )
].copy()

print("Rows after removal:", len(bld_final))

Rows after removal: 33

In [25]:
print(
    bld_final[
        bld_final["Building name"].str.contains(
            "Athenaeum|State Library Rail",
            case=False,
            na=False
        )
    ][
        [
            "Building name",
            "Street address",
            "Predominant space use",
            "Accessibility rating"
        ]
    ]
)

                     Building name                             Street address  \
198  Athenaeum Library and Theatre  184-192 Collins Street MELBOURNE VIC 3000

                     Predominant space use  Accessibility rating
198  Performances, Conferences, Ceremonies                   3.0

In [26]:
cols = [
    "Property ID",
    "Building name",
    "Street address",
    "CLUE small area",
    "Predominant space use",
    "Accessibility type",
    "Accessibility type description",
    "Accessibility rating",
    "Latitude",
    "Longitude"
]

bld_out = bld_final[cols].copy()

bld_out.to_csv(
    "buildings_refuge_final.csv",
    index=False
)

print("Saved rows:", len(bld_out))

Saved rows: 33