In [300]:
import pandas as pd

path = "landmarks.csv"
data = pd.read_csv(path)

data.head()

,Theme,Sub Theme,Feature Name,Co-ordinates
0,Vacant Land,Current Construction Site - Commercial,Railway Good Shed No 2,"-37.8211371302179, 144.951378883631"
1,Transport,Railway Station,Parliament Railway Station,"-37.8116061787171, 144.973017263156"
2,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),North Melbourne Recreation Reserve,"-37.7988345257153, 144.941452061463"
3,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Princes Park,"-37.7870161727156, 144.961115214367"
4,Office,Office,Donor Tissue Bank of Victoria,"-37.8248231859563, 144.965169035668"

In [301]:
print("Rows and columns:", data.shape)

print("Column names:")
print(data.columns.tolist())

print("Data types:")
print(data.dtypes)

print("First 5 rows:")
display(data.head())

Rows and columns: (242, 4)
Column names:
['Theme', 'Sub Theme', 'Feature Name', 'Co-ordinates']
Data types:
Theme           object
Sub Theme       object
Feature Name    object
Co-ordinates    object
dtype: object
First 5 rows:

,Theme,Sub Theme,Feature Name,Co-ordinates
0,Vacant Land,Current Construction Site - Commercial,Railway Good Shed No 2,"-37.8211371302179, 144.951378883631"
1,Transport,Railway Station,Parliament Railway Station,"-37.8116061787171, 144.973017263156"
2,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),North Melbourne Recreation Reserve,"-37.7988345257153, 144.941452061463"
3,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Princes Park,"-37.7870161727156, 144.961115214367"
4,Office,Office,Donor Tissue Bank of Victoria,"-37.8248231859563, 144.965169035668"

In [302]:
miss = data.isna().sum().sort_values(ascending=False)

display(miss)

Theme           0
Sub Theme       0
Feature Name    0
Co-ordinates    0
dtype: int64

In [303]:
miss_sum = pd.DataFrame({
    "missingcount": data.isna().sum(),
    "missingpercent": data.isna().mean() * 100
}).sort_values("missingpercent", ascending=False)

display(miss_sum)

              missingcount  missingpercent
Theme                    0             0.0
Sub Theme                0             0.0
Feature Name             0             0.0
Co-ordinates             0             0.0

In [304]:
dups = data.duplicated().sum()

print("Duplicate rows:", dups)

Duplicate rows: 0

In [305]:
for col in ["Theme", "Sub Theme"]:
    if col in data.columns:
        print(f"\nUnique values in {col}:")
        print(data[col].value_counts(dropna=False).head(30))

Unique values in Theme:
Theme
Leisure/Recreation                      63
Place Of Assembly                       40
Place of Worship                        31
Transport                               26
Community Use                           21
Education Centre                        13
Health Services                         11
Office                                  11
Mixed Use                               11
Purpose Built                            4
Vacant Land                              3
Retail                                   3
Residential Accommodation                2
Warehouse/Store                          1
Industrial                               1
Specialist Residential Accommodation     1
Name: count, dtype: int64

Unique values in Sub Theme:
Sub Theme
Informal Outdoor Facility (Park/Garden/Reserve)    37
Church                                             30
Railway Station                                    23
Art Gallery/Museum                                 19
Theatre Live                                       15
Major Sports & Recreation Facility                 14
Public Buildings                                   13
Office                                             11
Public Hospital                                     7
Retail/Office/Carpark                               5
Primary Schools                                     4
Function/Conference/Exhibition Centre               4
Outdoor Recreation Facility (Zoo, Golf Course)      4
Tertiary (University)                               4
Police Station                                      3
Indoor Recreation Facility                          3
Private Hospital                                    3
Retail/Office                                       3
Dwelling (House)                                    2
Observation Tower/Wheel                             2
Visitor Centre                                      2
School - Primary and Secondary Education            2
Secondary Schools                                   2
Film & RV Studio                                    2
Retail/Office/Residential/Carpark                   2
Department Store                                    2
Private Sports Club/Facility                        2
Medical Services                                    1
Current Construction Site - Commercial              1
Retail                                              1
Name: count, dtype: int64

In [306]:
desc = data.describe(include="all").T

display(desc)

,count,unique,top,freq
Theme,242,16,Leisure/Recreation,63
Sub Theme,242,49,Informal Outdoor Facility (Park/Garden/Reserve),37
Feature Name,242,233,Parliament Railway Station,4
Co-ordinates,242,242,"-37.8211371302179, 144.951378883631",1

In [307]:
geo_col = "Co-ordinates"

print(data[geo_col].head())
print("Missing coordinates:", data[geo_col].isna().sum())
print("Unique coordinates:", data[geo_col].nunique())

0    -37.8211371302179, 144.951378883631
1    -37.8116061787171, 144.973017263156
2    -37.7988345257153, 144.941452061463
3    -37.7870161727156, 144.961115214367
4    -37.8248231859563, 144.965169035668
Name: Co-ordinates, dtype: object
Missing coordinates: 0
Unique coordinates: 242

In [308]:
cord = data["Co-ordinates"].str.split(",", expand=True)

data["lat"] = pd.to_numeric(cord[0].str.strip(), errors="coerce")
data["lon"] = pd.to_numeric(cord[1].str.strip(), errors="coerce")

display(data[["Feature Name", "Co-ordinates", "lat", "lon"]].head())

,Feature Name,Co-ordinates,lat,lon
0,Railway Good Shed No 2,"-37.8211371302179, 144.951378883631",-37.821137,144.951379
1,Parliament Railway Station,"-37.8116061787171, 144.973017263156",-37.811606,144.973017
2,North Melbourne Recreation Reserve,"-37.7988345257153, 144.941452061463",-37.798835,144.941452
3,Princes Park,"-37.7870161727156, 144.961115214367",-37.787016,144.961115
4,Donor Tissue Bank of Victoria,"-37.8248231859563, 144.965169035668",-37.824823,144.965169

In [309]:
print("Missing latitude:", data["lat"].isna().sum())
print("Missing longitude:", data["lon"].isna().sum())

Missing latitude: 0
Missing longitude: 0

In [310]:
print("Latitude:", data["lat"].min(), "to", data["lat"].max())
print("Longitude:", data["lon"].min(), "to", data["lon"].max())

Latitude: -37.8485201804496 to -37.7812684282825
Longitude: 144.908190706069 to 144.989400751664

In [311]:
name_cnt = data["Feature Name"].value_counts()

name_dup = name_cnt[name_cnt > 1]
display(name_dup)

Feature Name
Parliament Railway Station           4
Melbourne Central Railway Station    4
Victoria Police                      3
Flagstaff Railway Station            2
Name: count, dtype: int64

In [312]:
same = data[data["Feature Name"].isin(name_dup.index)]

display(
    same.sort_values("Feature Name")
)

,Theme,Sub Theme,Feature Name,Co-ordinates,lat,lon
25,Transport,Railway Station,Flagstaff Railway Station,"-37.8122356514626, 144.956318211113",-37.812236,144.956318
119,Transport,Railway Station,Flagstaff Railway Station,"-37.8116384403974, 144.9561186805",-37.811638,144.956119
5,Transport,Railway Station,Melbourne Central Railway Station,"-37.8100167030855, 144.963789344893",-37.810017,144.963789
204,Transport,Railway Station,Melbourne Central Railway Station,"-37.8097759325888, 144.962670059539",-37.809776,144.962670
219,Transport,Railway Station,Melbourne Central Railway Station,"-37.8105992402369, 144.96169061383",-37.810599,144.961691
220,Transport,Railway Station,Melbourne Central Railway Station,"-37.8108930047401, 144.963100728702",-37.810893,144.963101
1,Transport,Railway Station,Parliament Railway Station,"-37.8116061787171, 144.973017263156",-37.811606,144.973017
92,Transport,Railway Station,Parliament Railway Station,"-37.8127621113552, 144.973433796529",-37.812762,144.973434
132,Transport,Railway Station,Parliament Railway Station,"-37.8095762219384, 144.972330132127",-37.809576,144.972330
233,Transport,Railway Station,Parliament Railway Station,"-37.8121572789173, 144.973742010011",-37.812157,144.973742
86,Community Use,Police Station,Victoria Police,"-37.8219773910249, 144.953398014034",-37.821977,144.953398
140,Community Use,Police Station,Victoria Police,"-37.8164849024046, 144.966486801188",-37.816485,144.966487
188,Community Use,Police Station,Victoria Police,"-37.8003121288849, 144.954697453742",-37.800312,144.954697

In [313]:
park = data[
    data["Sub Theme"].eq(
        "Informal Outdoor Facility (Park/Garden/Reserve)"
    )
].copy()

print("Park records:", len(park))
display(park.head(10))

Park records: 37

,Theme,Sub Theme,Feature Name,Co-ordinates,lat,lon
2,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),North Melbourne Recreation Reserve,"-37.7988345257153, 144.941452061463",-37.798835,144.941452
3,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Princes Park,"-37.7870161727156, 144.961115214367",-37.787016,144.961115
6,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Argyle Square,"-37.8031480577285, 144.965761295089",-37.803148,144.965761
12,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Kings Domain,"-37.8255239795833, 144.974107925144",-37.825524,144.974108
17,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Federation Square,"-37.8178516571684, 144.968963600783",-37.817852,144.968964
21,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Flagstaff Gardens,"-37.8111222889277, 144.954696055235",-37.811122,144.954696
23,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Westgate Park,"-37.8314918578874, 144.908824792698",-37.831492,144.908825
26,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Newmarket Reserve,"-37.7878473341234, 144.922972125346",-37.787847,144.922972
27,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),J.J Holland Park,"-37.7982358832177, 144.923837074813",-37.798236,144.923837
30,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Fitzroy Gardens,"-37.8129616331579, 144.980455714669",-37.812962,144.980456

In [314]:
libr = data[
    data["Feature Name"].str.contains(
        "Library",
        case=False,
        na=False
    )
    |
    data["Sub Theme"].str.contains(
        "Library",
        case=False,
        na=False
    )
].copy()

keep = [
    "Public Buildings",
    "Visitor Centre",
    "Art Gallery/Museum"
]

publ = data[
    data["Sub Theme"].isin(keep)
].copy()

print("Parks:", len(park))
print("Libraries:", len(libr))
print("Candidate public places:", len(publ))

Parks: 37
Libraries: 2
Candidate public places: 34

In [315]:
refu = pd.concat(
    [park, libr, publ],
    ignore_index=True
)

refu = refu.drop_duplicates(
    subset=["Feature Name", "lat", "lon"]
)

print("Total candidates:", len(refu))
display(refu.head(20))

Total candidates: 72

,Theme,Sub Theme,Feature Name,Co-ordinates,lat,lon
0,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),North Melbourne Recreation Reserve,"-37.7988345257153, 144.941452061463",-37.798835,144.941452
1,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Princes Park,"-37.7870161727156, 144.961115214367",-37.787016,144.961115
2,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Argyle Square,"-37.8031480577285, 144.965761295089",-37.803148,144.965761
3,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Kings Domain,"-37.8255239795833, 144.974107925144",-37.825524,144.974108
4,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Federation Square,"-37.8178516571684, 144.968963600783",-37.817852,144.968964
5,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Flagstaff Gardens,"-37.8111222889277, 144.954696055235",-37.811122,144.954696
6,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Westgate Park,"-37.8314918578874, 144.908824792698",-37.831492,144.908825
7,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Newmarket Reserve,"-37.7878473341234, 144.922972125346",-37.787847,144.922972
8,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),J.J Holland Park,"-37.7982358832177, 144.923837074813",-37.798236,144.923837
9,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Fitzroy Gardens,"-37.8129616331579, 144.980455714669",-37.812962,144.980456
10,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Richmond Football Club,"-37.8216740022008, 144.988156318781",-37.821674,144.988156
11,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Royal Botanic Gardens,"-37.8306631583233, 144.980850432751",-37.830663,144.980850
12,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Darling Square,"-37.81299206932, 144.989062559512",-37.812992,144.989063
13,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Parliament Reserve,"-37.809852620638, 144.973462202839",-37.809853,144.973462
14,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Macarthur Square,"-37.7983318676737, 144.971514146104",-37.798332,144.971514
15,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Shrine of Rembrance Reserve,"-37.8320733992876, 144.973628364465",-37.832073,144.973628
16,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Treasury Gardens,"-37.8143993575938, 144.975952335785",-37.814399,144.975952
17,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Queen Victoria Gardens,"-37.8216381244891, 144.971049530478",-37.821638,144.971050
18,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),New Quay,"-37.8152178789077, 144.941617889032",-37.815218,144.941618
19,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Sandridge Rail Bridge,"-37.8201763042794, 144.96298113724",-37.820176,144.962981

In [316]:
print("Dataset size:", data.shape)
print("Missing values:", int(data.isna().sum().sum()))
print("Duplicate rows:", int(data.duplicated().sum()))
print("Unique themes:", data["Theme"].nunique())
print("Unique sub themes:", data["Sub Theme"].nunique())
print("Unique feature names:", data["Feature Name"].nunique())
print("Unique coordinates:", data["Co-ordinates"].nunique())
print("Park records:", len(park))
print("Library records:", len(libr))
print("Possible public spaces:", len(publ))

Dataset size: (242, 6)
Missing values: 0
Duplicate rows: 0
Unique themes: 16
Unique sub themes: 49
Unique feature names: 233
Unique coordinates: 242
Park records: 37
Library records: 2
Possible public spaces: 34

In [317]:
refu.to_csv(
    "landmarks_refuge_candidates.csv",
    index=False
)

print("Saved:", len(refu), "records")

Saved: 72 records